### ISSUE TITLE
掘金的目录不错，要不要也加一个

### ISSUE THREAD

**Issue by mqycn** [su37josephxia/smarty-press#18]
比如：https://juejin.im/post/6850037267466190856#heading-0

![微信图片_20200905173051](https://user-images.githubusercontent.com/3360397/92302280-93651280-ef9d-11ea-8732-e71298689b90.png)

**Comment by williamhatch** [comment]
@mqycn 你做么？

**Comment by mqycn** [comment]
> @mqycn 你做么？

我来做~
