### ISSUE TITLE
发布功能： Vercel发布

### ISSUE THREAD

**Issue by su37josephxia** [su37josephxia/smarty-press#2]
可以参考一下这个网站一旦部署就可以免费生成网页
https://github.com/apps/vercel

**Comment by mqycn** [comment]
已经 大圣 老师 搞懂了，我注册了个小号 测试成功了。

直接安装后，全部自动的。

**Comment by mqycn** [comment]
已经完成，git pull 或者 发起pr 时，自动执行 yarn build 生成静态并发布到 vercel
