### ISSUE TITLE
针对billbill视频内嵌的格式调整

### ISSUE THREAD

**Issue by su37josephxia** [su37josephxia/smarty-press#32]
目前内嵌b栈视频时 视频过小需要调整到合理值。并且需要考虑手机适配
![image](https://user-images.githubusercontent.com/9651900/133064460-230012d4-ce95-44eb-b892-16af7e221828.png)

**Comment by CaesarAuditore** [comment]
不大懂手机咋适配，直接弄成手机宽度时百分比宽度，这样可以不。
![image](https://user-images.githubusercontent.com/44400132/133407690-b527ef38-6be4-47bf-9995-1e3398203a6b.png)
![image](https://user-images.githubusercontent.com/44400132/133407617-e0647b09-07e4-4759-9ad0-359d8409e5b0.png)

**Comment by su37josephxia** [comment]
你提一下试试呀

**Comment by itgou** [comment]
这个有人做没有， 没人做的话，我来占坑了

**Comment by CaesarAuditore** [comment]
> 这个有人做没有， 没人做的话，我来占坑了

我写了
