### ISSUE TITLE
欢迎界面美化

### ISSUE THREAD

**Issue by su37josephxia** [su37josephxia/smarty-press#4]
![image](https://user-images.githubusercontent.com/9651900/91366636-e53bc900-e836-11ea-8fbf-891808bc9e98.png)
目前这个还是 太丑了 我也没什么美感 需要有心人。

- 另外还需要解决一下自动刷新手 最好能够保留标题的问题

**Comment by williamhatch** [comment]
我来试一下哈

**Comment by williamhatch** [comment]
submit PR :)

**Comment by mqycn** [comment]
https://github.com/su37josephxia/smarty-press/pull/19 已经合并
